name: Build
on: [push]
jobs:
  VS-2022:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Release]
        platform: ["Any CPU"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Use NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore nuget packages
        run: nuget restore UnityModInstaller.sln
      
      - name: Build all Sample solutions
        run: msbuild UnityModInstaller.sln /p:configuration="${{ matrix.configuration }}" /p:platform="${{ matrix.platform }}"

      - uses: actions/upload-artifact@v3
        with:
          name: UnityModInstaller
          path: |
            UnityModInstaller\UnityAssetReplacer\bin\Release\install.exe
