name: Build
on: 
  push:
    branches:
      - '**'

jobs:
  VS-2022:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Release]
        platform: ["Any CPU"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: packages
          key: umi-${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} #hash of project files
          restore-keys: |
            umi-${{ runner.os }}-nuget-

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Use NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore nuget packages
        run: nuget restore UnityModInstaller.sln
      
      - name: Build
        run: msbuild UnityModInstaller.sln /p:configuration="${{ matrix.configuration }}" /p:platform="${{ matrix.platform }}"

      - name: Bundle
        run: |
          Get-ChildItem -Path UnityAssetReplacer/bin/Release/install.exe, LICENSE.txt, README.md | Compress-Archive -DestinationPath UnityModInstaller.zip

      - uses: actions/upload-artifact@v3
        with:
          name: UnityModInstaller
          path: UnityModInstaller.zip
